account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user-register"),
    path("login/", views.UserLoginView.as_view(), name="user-login"),
    path("logout/", views.UserLogoutView.as_view(), name="user-logout"),
    path("profile/", views.UserProfileView.as_view(), name="user-profile"),
    path("feeds/<str:username>/", views.UserFeedsView.as_view(), name="user-feeds"),
    path("reset/", views.UserPasswordResetView.as_view(), name="user-password-reset"),
    path(
        "reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="user-password-reset-done",
    ),
    path(
        "confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="user-password-reset-confirm",
    ),
    path(
        "confirm/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="user-password-reset-complete",
    ),
    path("follow/<int:user_id>/", views.UserFollowView.as_view(), name="user-follow"),
    path(
        "unfollow/<int:user_id>/",
        views.UserUnFollowView.as_view(),
        name="user-unfollow",
    ),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(),name="post-detail"),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(),name="post-delete"),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(),name="post-update"),
    path('post/create/', views.PostCreateView.as_view(),name="post-create")
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account'))
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
    <p class="alert alert-{{message.tags}}" > {{message}} </p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url "home:home" %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url "account:user-profile" %}">Profile</a>
        <a class="nav-link active" href="{% url "account:user-feeds" request.user.username %}">Feeds</a>
        <a class="nav-link active" href="{% url "account:user-logout" %}">Logout</a>
        {% else %}
        <a class="nav-link active" href="{% url "account:user-register" %}">Register</a>
        <a class="nav-link active" href="{% url "account:user-login" %}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>